/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppSettingsIndexImport } from './routes/_app/settings/index'

// Create Virtual Routes

const AppSettingsEnumLazyImport = createFileRoute('/_app/settings/enum')()
const AppFleetAircraftLazyImport = createFileRoute('/_app/fleet/aircraft')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsIndexRoute = AppSettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsEnumLazyRoute = AppSettingsEnumLazyImport.update({
  path: '/settings/enum',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/enum.lazy').then((d) => d.Route),
)

const AppFleetAircraftLazyRoute = AppFleetAircraftLazyImport.update({
  path: '/fleet/aircraft',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/fleet/aircraft.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/fleet/aircraft': {
      preLoaderRoute: typeof AppFleetAircraftLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/enum': {
      preLoaderRoute: typeof AppSettingsEnumLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/': {
      preLoaderRoute: typeof AppSettingsIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AppRoute.addChildren([
    AppIndexRoute,
    AppFleetAircraftLazyRoute,
    AppSettingsEnumLazyRoute,
    AppSettingsIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
