/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppSettingsIndexImport } from './routes/_app/settings/index'
import { Route as AppSettingsEnumImport } from './routes/_app/settings/enum'
import { Route as AppFleetAircraftImport } from './routes/_app/fleet/aircraft'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsIndexRoute = AppSettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsEnumRoute = AppSettingsEnumImport.update({
  path: '/settings/enum',
  getParentRoute: () => AppRoute,
} as any)

const AppFleetAircraftRoute = AppFleetAircraftImport.update({
  path: '/fleet/aircraft',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/fleet/aircraft': {
      preLoaderRoute: typeof AppFleetAircraftImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/enum': {
      preLoaderRoute: typeof AppSettingsEnumImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/': {
      preLoaderRoute: typeof AppSettingsIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AppRoute.addChildren([
    AppIndexRoute,
    AppFleetAircraftRoute,
    AppSettingsEnumRoute,
    AppSettingsIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
