### test

GET http://localhost:8000/api/platform/test
Authorization: Bearer 7f5f32d3586d4f8394204da07635d35d

### enums

GET http://localhost:8000/api/platform/enums
Content-Type: application/json
Authorization: Bearer 7f5f32d3586d4f8394204da07635d35d

### get enum

GET http://localhost:8000/api/platform/enums/Aircraft.AcType
Content-Type: application/json
Authorization: Bearer 7f5f32d3586d4f8394204da07635d35d

### members

GET http://localhost:8000/api/platform/enums/Aircraft.AcType/members
Content-Type: application/json

### users

GET http://localhost:8000/api/platform/users
Content-Type: application/json
Authorization: Bearer 52f13d053cd4470a9b43a7e9eb21f456
