### test

GET http://localhost:8000/api/platform/test

### enums

GET http://localhost:8000/api/platform/enums
Content-Type: application/json

### get enum

GET http://localhost:8000/api/platform/enums/Aircraft.AcType
Content-Type: application/json

### members

GET http://localhost:8000/api/platform/enums/Aircraft.AcType/members
Content-Type: application/json

###
