### test

GET http://localhost:8000/api/platform/test
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### info

GET http://localhost:8000/api/platform/server/info
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### privileges

GET http://localhost:8000/api/platform/privileges
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### enums

GET http://localhost:8000/api/platform/enums
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### get enum

GET http://localhost:8000/api/platform/enums/Aircraft.AcType
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### get enum not found

GET http://localhost:8000/api/platform/enums/not.found
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### create enum

POST http://localhost:8000/api/platform/enums
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

{
  "id": "test",
  "name": "Test",
  "description": "description"
}

### update enum

POST http://localhost:8000/api/platform/enums/test
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

{
  "id": "test",
  "name": "Test",
  "description": ""
}

### update enum members

POST http://localhost:8000/api/platform/enums/test/members
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

{
  "members": [
    {
      "label": "0",
      "value": "0"
    },
    {
      "label": "A",
      "value": "a"
    }
  ]
}

### users

GET http://localhost:8000/api/platform/users
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381

### users by role

GET http://localhost:8000/api/platform/users?roleId=rol-system-admin
Content-Type: application/json
Authorization: Bearer aed1edb934a44923be6635dcbb9e4381
